// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhUgXeP9WH5qjZW8Iz0h-yY4HFAvRFi0M',
    appId: '1:967772981731:web:330d7cc8d84de2c710b8d6',
    messagingSenderId: '967772981731',
    projectId: 'instax-7d4ff',
    authDomain: 'instax-7d4ff.firebaseapp.com',
    storageBucket: 'instax-7d4ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_X-ZnlAduyXx-jlZaMLpf6g13Pt9s9PU',
    appId: '1:967772981731:android:2c455a35d576768a10b8d6',
    messagingSenderId: '967772981731',
    projectId: 'instax-7d4ff',
    storageBucket: 'instax-7d4ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdNPuySM5Ix2HLR3F8PP5BMq3xwV3hoG0',
    appId: '1:967772981731:ios:01b21548d30293bd10b8d6',
    messagingSenderId: '967772981731',
    projectId: 'instax-7d4ff',
    storageBucket: 'instax-7d4ff.appspot.com',
    iosBundleId: 'com.example.skillsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdNPuySM5Ix2HLR3F8PP5BMq3xwV3hoG0',
    appId: '1:967772981731:ios:140fea4fac73c68b10b8d6',
    messagingSenderId: '967772981731',
    projectId: 'instax-7d4ff',
    storageBucket: 'instax-7d4ff.appspot.com',
    iosBundleId: 'com.example.skillsProject.RunnerTests',
  );
}
